### ISSUE TITLE
Support freethreaded toolchains and wheels

### ISSUE THREAD

**Issue by aignas** [bazelbuild/rules_python#2386]
Scope:
* [x] Adding URLs that reference indygreg freethreaded toolchains. (#2372)
* [x] Running coverage using freethreaded toolchains. (#2372)
* [x] Depending on whls when freethreaded toolchains are used. (#2460)
* [x] Using a freethreaded toolchain interpreter in `pip.parse` rules to build from sdist. (#2406).

Better support for sdist building should be done separately.
